channels:
- conda-forge
dependencies:
- autodocsumm
- breathe
- catch2 >=3.0.0
- click
- cmake
- doxygen >=1.9.5
- eigen
- enstat >=0.5.0
- fmt
- furo
- gmatelastic >=0.5.0
- gmatelastoplasticqpot >=0.17.0
- gmattensor >=0.10.2
- goosefem >=1.3.0
- goosehdf5 >=0.20.0
- goosempl
- gooseslurm
- graphviz
- graphviz
- h5py
- mathjax
- nested_dict
- ninja
- numpy
- numpy
- openscienceplot_matplotlib
- parallel
- path
- pre-commit
- prrng >1.1.0
- pybind11
- python
- python-cppcolormap
- python-frictionqpotfem >0.20.1
- python-gmatelastic >0.5.0
- python-gmatelastoplasticqpot >=0.17.0
- python-gmattensor >0.9.0
- python-goosefem >=1.3.0
- python-prrng
- python-qpot >=0.12.1
- qpot
- scikit-build
- scipy
- setuptools_scm
- shelephant
- sphinx
- sphinx_rtd_theme
- sphinx-tabs
- tqdm
- xdmfwrite_h5py
- xsimd
- xtensor >=0.24.2
- xtensor-python
