channels:
- conda-forge
dependencies:
- cmake
- cpppath
- docopt.cpp
- enstat
- fmt
- frictionqpotfem
- gmatelastoplasticqpot
- goosefem
- goosehdf5
- gooseslurm
- h5py
- highfive
- make
- nested_dict
- ninja
- parallel
- pre-commit
- python
- python-frictionqpotfem
- python-gmatelastoplasticqpot
- python-goosefem
- python-prrng
- python-qpot
- qpot
- setuptools_scm
- shelephant
- tqdm
- xsimd
- xtensor
# - xtensor-blas
- xtensor-python
