channels:
- conda-forge
dependencies:
- autodocsumm
- click
- cmake
- cpppath
- docopt.cpp
- enstat
- fmt
- frictionqpotfem >=0.20.1
- gmatelastic >=0.5.0
- gmatelastoplasticqpot >=0.17.0
- gmattensor >=0.10.2
- goosefem >=1.3.0
- goosehdf5 >=0.17.0
- goosempl
- gooseslurm
- h5py
- highfive
- make
- nested_dict
- ninja
- numpy
- openscienceplot_matplotlib
- parallel
- pre-commit
- pybind11
- python
- python-cppcolormap
- python-frictionqpotfem >=0.20.1
- python-gmatelastic >0.5.0
- python-gmatelastoplasticqpot >=0.17.0
- python-gmattensor >0.9.0
- python-goosefem >=1.3.0
- python-prrng
- python-qpot
- qpot >=0.12.1
- scikit-build
- setuptools_scm
- shelephant
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py
- xsimd
- xtensor >=0.24.2
- xtensor-blas
- xtensor-python
