channels:
  - conda-forge
dependencies:
  - cmake
  - cpppath
  - docopt.cpp
  - fmt
  - frictionqpotfem
  - gitpython
  - gmatelastoplasticqpot
  - goosefem
  - goosehdf5
  - gooseslurm
  - h5py
  - highfive
  - make
  - ninja
  - parallel
  - python
  - python-frictionqpotfem
  - python-gmatelastoplasticqpot
  - python-goosefem
  - python-qpot
  - qpot
  - setuptools_scm
  - shelephant
  - tqdm
  - xsimd
  - xtensor
  - xtensor-blas
  - xtensor-python
