channels:
- conda-forge
dependencies:
- autodocsumm
- cmake
- cpppath
- docopt.cpp
- enstat
- fmt
- frictionqpotfem
- gmatelastoplasticqpot
- goosefem
- goosehdf5
- goosempl
- gooseslurm
- h5py
- highfive
- make
- nested_dict
- ninja
- parallel
- pre-commit
- python
- python-cppcolormap
- python-frictionqpotfem
- python-gmatelastoplasticqpot
- python-goosefem
- python-prrng
- python-qpot
- qpot
- setuptools_scm
- shelephant
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py
- xsimd
- xtensor
- xtensor-blas
- xtensor-python
