channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.5.0
- goosehdf5 >=0.20.0
- goosempl
- gooseslurm
- h5py
- nested_dict
- numpy
- openscienceplot_matplotlib
- path
- parallel
- pre-commit
- pybind11
- python
- python-cppcolormap
- python-frictionqpotfem >0.20.1
- python-gmatelastic >0.5.0
- python-gmatelastoplasticqpot >=0.17.0
- python-gmattensor >0.9.0
- python-goosefem >=1.3.0
- python-prrng
- python-qpot >=0.12.1
- scikit-build
- setuptools_scm
- shelephant
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py
