channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.5.0
- furo
- goosehdf5 >=0.22.0
- goosempl
- gooseslurm
- h5py
- numpy
- parallel
- pre-commit
- pytest
- python >=3.6
- python-cppcolormap
- python-frictionqpotfem >=0.23.1
- python-gmatelastic >0.5.0
- python-gmatelastoplasticqpot >=0.18.2
- python-gmattensor >0.9.0
- python-goosefem >=1.4.0
- python-prrng
- python-qpot >=0.12.1
- setuptools_scm
- shelephant
- sphinx
- sphinx-argparse
- tqdm
- xdmfwrite_h5py
