channels:
  - conda-forge
dependencies:
  - frictionqpotfem
  - goosefem
  - gmatelastoplasticqpot
  - python
  - python-goosefem
  - python-gmatelastoplasticqpot
  - h5py
  - cmake
  - make
  - xtensor
  - xtensor-blas
  - xsimd
  - highfive
  - cpppath
  - docopt.cpp
  - fmt
  - parallel
  - gooseslurm
  - goosehdf5
  - tqdm
  - setuptools_scm
  - shelephant
