name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        code:
        - Flow.py
        - MeasureDynamics.py
        - PinAndTrigger.py
        - slurm.py
        - storage.py
        - System.py
        - tag.py
        - tools.py
        - Trigger.py

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.code }}
    runs-on: ubuntu-latest

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Install plot style
      run: python -c "import GooseMPL; GooseMPL.copy_style()"

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=0.0" >> $GITHUB_ENV

    - name: Install module
      run: python -m pip install . -vv

    - name: Run tests
      working-directory: tests
      run: python ${{ matrix.code }}
