name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.code }}
    runs-on: ubuntu-latest

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        cache-env: true

    - name: Install plot style
      run: python -c "import GooseMPL; GooseMPL.copy_style()"

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=0.0" >> $GITHUB_ENV

    - name: Install module
      run: python -m pip install . -vv

    - name: Run tests
      working-directory: tests
      run: |
        python MeasureDynamics.py
        python PinAndTrigger.py
        python slurm.py
        python storage.py
        python System.py
        python tag.py
        python tools.py
        python Trigger.py
        python Flow.py
